name: Unit Test and Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m pytest

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
    - name: Publish test results
      uses: actions/publish-test-results@v1
      with:
        test-results-files: test-results.xml
